# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H0PR_wAvIG_Ybo47S0UA4LQZmrW7cBRf
"""



import os

# 1. DELETE the text inside the quotes and paste your Kaggle credentials
os.environ['KAGGLE_USERNAME'] = "roto4321p"
os.environ['KAGGLE_KEY'] = "KGAT_f849c330cdcc2f68a4cf8b0b70eda83d"

# 2. Install the tool that handles the data transfer


# 3. Pull the 3GB dataset directly to Google's cloud server
import kagglehub
train_path = kagglehub.model_download("vbookshelf/rice-leaf-diseases-tf-model/tensorFlow2/default/1")
path = kagglehub.dataset_download("vipoooool/new-plant-diseases-dataset")

print("--------------------------------------------------")
print("SUCCESS! The 3GB dataset is now on Google's server.")
print("Folder Location:", path)



import tensorflow as tf
from tensorflow.keras import layers, models

# 1. We create the 'Base' using Google's MobileNetV2
# It's like a student who already knows how to see shapes/colors
base_model = tf.keras.applications.MobileNetV2(
    input_shape=(224, 224, 3),
    include_top=False,
    weights='imagenet'
)

# 2. We 'freeze' the base so it doesn't forget the basics
base_model.trainable = False

# 3. We add the 'AgriGuard' specialized layer on top
model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.2), # Helps prevent the AI from 'cheating' by memorizing
    layers.Dense(38, activation='softmax') # 38 is the number of plant diseases we are tracking
])

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

print("--------------------------------------------------")
print("BRAIN INITIALIZED: AgriGuard is ready for school.")
model.summary()

from tensorflow.keras.preprocessing.image import ImageDataGenerator

# 1. Prepare the 'Feeding Tube' for the AI
# We shrink the photos to 224x224 so the GPU can process them faster
datagen = ImageDataGenerator(rescale=1./255, validation_split=0.2)

train_generator = datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode='sparse',
    subset='training'
)

val_generator = datagen.flow_from_directory(
    train_path,
    target_size=(224, 224),
    batch_size=32,
    class_mode='sparse',
    subset='validation'
)

# 2. START THE TRAINING (The 'Fit' Phase)
# We start with 5 'Epochs' (5 full rounds of study)
history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=5
)

# Save the model so we can use it in our UI
model.save('agri_guard_brain.h5')
print("✅ SUCCESS: The AgriGuard Brain is saved as 'agri_guard_brain.h5'")

from google.colab import files
files.download('agri_guard_brain.h5')
